import type { NextPage } from "next";
import Head from "next/head";
import HomeHeader from "../components/Header/Header";
import HomeMedia from "../components/HomeMedia/HomeMedia";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
   return (
      <div className={styles.container}>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <HomeMedia/>
      </div>
   );
};

export default Home;
